name: Fetch iTunes Country codes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "0 2 * * *" # 02:00 UTC

permissions:
  contents: write

jobs:
  fetch-chunks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # split task into parallel chunks to avoid iTunes Search API throttling
        chunks: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] 
    env:
      total_chunks: 12
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests
    - name: Fetch iTunes Country codes
      run: python script/fetch_itunes_country_codes.py $total_chunks ${{matrix.chunks}} > ./c${{matrix.chunks}}.json
    - uses: actions/upload-artifact@v3
      with:
        name: chunks
        path: ./c${{matrix.chunks}}.json
  
  combine:
    runs-on: ubuntu-latest
    needs: [fetch-chunks]
    steps:       
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%b-%d')" >> $GITHUB_OUTPUT
      - name: Get unix timestamp
        id: unix
        run: echo "date=$(date +'%s')" >> $GITHUB_OUTPUT
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Combine chunks
        id: changes
        run: |
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          python script/combine_chunks.py >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: (Automated) Updated iTunes Country codes
          file_pattern: 'itunes_country_codes.json'
      - name: Release
        uses: softprops/action-gh-release@v1
        if: env.CHANGELOG != 'identical'
        with:
          files: itunes_country_codes.json
          name: Update ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.unix.outputs.date }}
          body: ${{ env.CHANGELOG }}
